### ISSUE TITLE
What happened to Android Auto Support?

### ISSUE THREAD

**Issue by job-ad-promotion** [4phun/amproid#10]
I found this app by searching for ampache & android auto as I don't know how to hear my music (ampache) within the android auto app.

I saw in the changes, that android auto support was turned off, when the support of older android versions was added.
Is it either or? Either Android Auto or the older Android versions?
Is there a "workaround"? Can I somehow install the version before november last year (v1.11.2)?
Thank you for the app and your work on that!

**Comment by 4phun** [comment]
What happened was that Google rejected it. They never gave a reason why. I tried a number of times, I asked for the reason, but to no avail. There is no known workaround.

If you have some software development experience, you can download the source code and compile Amproid yourself. The only change needed is to uncomment the Android Auto part in AndroidManifest.xml.

I am planning on trying it again, but not in the very near future.

Thank you for your interest in Amproid.

**Comment by job-ad-promotion** [comment]
Hey 4phun, thank you so much for your quick response and your explanation. I thought it could be something like that (no obvious reason, except google) but was still hoping. Thanks again for the app!

PS. since google music is gone and they force everyone to youtube music, I wonder if they really think that youtube music is an alternative for google music - specially with mobile data being expensive and ... in the car!?!

**Comment by 4phun** [comment]
Hi @job-ad-promotion

Just wanted to let you know that Android Auto is back in Amproid. It does require Android 9 Pie or newer though.

Hope you'll give it another try. Your comments and suggests are welcomed here.

Thank you
