### ISSUE TITLE
.mp3 files do not play (.aac files do)

### ISSUE THREAD

**Issue by Tarnyko** [4phun/amproid#11]
Same server : **Ampache 4.2.5** running on **PHP 7.4.19**.
- **[Amdroid](https://f-droid.org/fr/packages/com.sound.ampache/)** (**last** version): both .mp3 & .aac files play;
- **Amproid** (version **2.0.15**): only .aac files play.

Although the cursor & controls are active on .mp3 songs, no sound comes out.
Both formats are set to "transcode: allowed".
"backend = ffmpeg" (ffmpeg & lame are present on the server).
Amdroid app plays them fine.
How is it possible to debug this?

**Comment by 4phun** [comment]
Hi,

This is very strange behavior. Amproid uses the device's built-in media player, as accessible from Java. It doesn't do its own decoding & output. So the only thing I can think of is maybe there is some problem with the device's MP3 decoder?
