### ISSUE TITLE
Brows and Playlist doesn't work

### ISSUE THREAD

**Issue by 4phun** [4phun/amproid#2]
I'm trying out version 1.1 I can connect to my server and music starts playing right away.  I get blank windows when I press on browse or press on playlists. I'm on a Pixel 3 using Android 10.

https://groups.google.com/d/msg/ampache/cqIisNFyJ0A/cvC_LvGOBAAJ

**Comment by 4phun** [comment]
Thank you for the feedback.

One of the goals I have set for version 1.2 is better error handling and error messages. To be honest Amproid currently lacking on that. Let's get back to this once 1.2 is out and we can get more info on the causes.

**Comment by lachlan-00** [comment]
Here are the screens. I think it has something to do with my smart lists for the playlists. but browse might just be the size of my library i haven't checked what method that one calls.

**edit to order of screens**
Main screen
![Screenshot_20200121-082846_Amproid](https://user-images.githubusercontent.com/1305249/72761693-866efb00-3c28-11ea-9a0f-a838edf3a077.jpg)


Tap Playlists and loading
![Screenshot_20200121-082908_Amproid](https://user-images.githubusercontent.com/1305249/72761660-6fc8a400-3c28-11ea-92fb-6fbf756aabc1.jpg)

Result is blank
![Screenshot_20200121-082902_Amproid](https://user-images.githubusercontent.com/1305249/72761667-75be8500-3c28-11ea-81b1-184d43466f50.jpg)

Go back home and tap browse

Loading
![Screenshot_20200121-082855_Amproid](https://user-images.githubusercontent.com/1305249/72761683-80791a00-3c28-11ea-8bc1-35a6eedb9978.jpg)

blank result
![Screenshot_20200121-082913_Amproid](https://user-images.githubusercontent.com/1305249/72761646-64757880-3c28-11ea-8cc6-b72aa2c1f6b1.jpg)

**Comment by 4phun** [comment]
New version 1.2 have just been uploaded to Play Store. Please give it a day or two before it becomes available.

With reference to our e-mail conversation: Network read timeout have been increased to 90 seconds. Connection timeout remained 25 seconds. The new version also has better error messages, this should help us determine the cause it if persists.

Please kindly test after update, and let me know the results.

> This is brilliant, thank you. It gave me the info I was looking for.
> Did some experiments and I think it's just that the network request is timing out due to all the work the server has to do before replying. I will have to increase it. I started to work on the error messages too.

**Comment by lachlan-00** [comment]
Guess what. the timeout and the update work correctly for me now!

**Comment by lachlan-00** [comment]
I see that it remembers my playlist on reload as well? That's basically all i need for an ampache client.

So would i be correct in thinking that shuffle is the original default?

**Comment by 4phun** [comment]
Great news! Thank you.

Yes, play mode including playlist position saved automatically and loaded on startup. You're correct, "Shuffle" is the default mode. Also switches back to "Shuffle" once the playlist is finished.

Appreciate you help. I am closing this issue now.
