### ISSUE TITLE
choose a default play mode or setting to disable autoplay

### ISSUE THREAD

**Issue by lachlan-00** [4phun/amproid#3]
I think it would be good to allow a choice of a start action that would refresh the playlist or continue where you left off

(Btw liking the visual updates you've made)

**Comment by 4phun** [comment]
Thank you!

I also did think about this.

In my opinion, smart lists should be started from the beginning every time, but regular playlists should be continued from wherever it was left off.

In the doc of XML examples, for playlist a "type" attribute is mentioned, but it seems to indicate whether the playlist is private or public. Which I don't even handle in Amproid yet.

So my plan was to ask you if you could include an indicator of whether the playlist is smartlist or not. Then I could use that. And at the same I would add support for the private/public flag too.

What do you think?

**Comment by lachlan-00** [comment]
the id of a smartlist will always be prefixed with "smart_" the id of a playlist is just the index number.
https://github.com/ampache/python3-ampache/blob/master/docs/xml-responses/playlists.xml

**Comment by lachlan-00** [comment]
isint or int(id) > 0 (not sure about the java call)
would be enough to determine based on the id.

**Comment by 4phun** [comment]
You make it too easy again :smile: This will be in next release.

(Java is strongly typed, id is handled as string, so it has to be the "startsWidth" method)

**Comment by 4phun** [comment]
This have been added to next release
