### ISSUE TITLE
allow download /cache of playlist

### ISSUE THREAD

**Issue by lachlan-00** [4phun/amproid#4]
Allow a cache or download of current playlist (limited amount?)

Would need to send record_play when the song is played instead of just streaming.

I do like to play something in the car but tend to cache my unplayed before leaving.

**Comment by 4phun** [comment]
This is in the plans already :smile: Will keep you posted.

**Comment by 4phun** [comment]
New release 1.7 contains the code to detect current network type (WIFI or mobile data or none, etc). It is now in use to better handle lost network connection, but is also a prerequisite for caching. Because caching should happen only while on WIFI. Planing to devote next release to caching.

**Comment by 4phun** [comment]
After lengthy deliberations, I decided not to include caching in Amproid because that could open the door for possible copyright related issues. Sorry and thank you.
