### ISSUE TITLE
Keeps randomly waking up and playing music

### ISSUE THREAD

**Issue by ncot-tech** [4phun/amproid#5]
On my phone I've noticed that if I use the lock screen camera or answer a call, when either of those two things have finished, Amproid wakes up and starts playing music.

Also if I try to quit it from the notification by pressing "x", I get a message saying it can't quit.

**Comment by 4phun** [comment]
Thank you for reporting the issue.

Please answer a few questions:
What Android version you use?
What Amproid version you use?
Does these happen while you're connected to Android Auto, or always?

Thank you in advance

**Comment by 4phun** [comment]
In version 1.9 I added a number of fixes in conjunction with this issue. Please re-open this issue if you continue to experience the issue.
