### ISSUE TITLE
issues with logon while testing next Ampache api

### ISSUE THREAD

**Issue by lachlan-00** [4phun/amproid#6]
Hey, i'm just testing to try and get the new api locked in and amproid is not able to login.

It tells me "Blank login token" on the playlists button when trying to browse

here's the response api5 is returning, the biggest change is that the api version is no longer numeric to match the server version
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<auth><![CDATA[9aa3efe9da2c4abc888301f18f00cf38]]></auth>
	<api><![CDATA[5.0.0]]></api>
	<session_expire><![CDATA[2020-10-14T12:18:12+10:00]]></session_expire>
	<update><![CDATA[2020-10-06T18:15:34+10:00]]></update>
	<add><![CDATA[2020-10-12T08:37:10+10:00]]></add>
	<clean><![CDATA[2020-10-12T08:36:56+10:00]]></clean>
	<songs><![CDATA[312591]]></songs>
	<albums><![CDATA[30369]]></albums>
	<artists><![CDATA[13112]]></artists>
	<playlists><![CDATA[38]]></playlists>
	<videos><![CDATA[14]]></videos>
	<catalogs><![CDATA[6]]></catalogs>
</root>

```

**Comment by 4phun** [comment]
Hi,
Thank you for the heads up. Yes, it's probably the version number. I will check it this weekend God willing. Is this in devel yet, or is there commit number I can check out to test?

**Comment by lachlan-00** [comment]
I'll update the develop demo server to the api branch and put the details here.

**Comment by lachlan-00** [comment]
I've kept this out as a separate branch for now but the versioning will be moving to follow the main release version so i'm trying to get ahead of myself and work out any possible issues before moving to develop.

feel free to use this server or the demo site for any testing, that's why i paid for it. ;)

https://develop.ampache.dev
demo
demodemo

**Comment by lachlan-00** [comment]
just confirming i set the version to 500000 and playlists were okay.

**Comment by lachlan-00** [comment]
annnnndddd reverting still fixes it.... must have been me! ill close this but use that test server for anything you want

**Comment by lachlan-00** [comment]
actually i think that was just my open session. but at peast that confirms it

**Comment by 4phun** [comment]
Hi,
I can confirm it is the change in the version number format, I fixed that. However, I use a simple query to validate the existing token before requesting a new one:
https://develop.ampache.dev/server/xml.server.php?action=playlist_generate&auth=token&limit=1&format=index
Seems that "total_count" is now missing from the XML reply. Is this by design? If so, can I ask to please add it back?
Thank you

**Comment by lachlan-00** [comment]
we were taking total_count out because it seems a bit superfluous when to u can just could the returned elements

what do to u do with it?

**Comment by 4phun** [comment]
I'm just using it to check the results. These sort of fields usually included in all kinds of APIs and protocols mainly for verification purposes.

**Comment by lachlan-00** [comment]
i guess alternatively it might be a good idea to include totals of the object you're searching?

as is search playlists; return a:
```
<total_count type=playlists>24</total_count>
```

I might add in a totals/cache value somewhere that can fill this up without having to count everything.

**Comment by lachlan-00** [comment]
i reverted the removal but i'm going to change it to total items tomorrow

**Comment by 4phun** [comment]
Cool, sounds great, thank you!

**Comment by 4phun** [comment]
FYI, just released Amproid V1.10 that includes fixes discussed here, for Ampache 5.0.0

**Comment by lachlan-00** [comment]
awesome, i wanted to give you plenty of time to check things out so glad i did!

**Comment by 4phun** [comment]
The saga continues... Google keeps rejecting the new version. Looks like I either have to give up, or rewrite the entire app using the latest and greatest API. Not sure if I have enough time for that. Anyhow, just wanted to let you know.

**Comment by lachlan-00** [comment]
jeez goog, thanks for your update

**Comment by 4phun** [comment]
OK finally managed to free up some time and was able to push version 1.11.3 through. The compromise: had to drop Android Auto support (for now). Also dropped support for Android 5 Lollipop and 6 Marshmallow, minimum now is 7 Nougat. But at least this will be able to handle the changes to Ampache 5 login.

**Comment by lachlan-00** [comment]
i've seen a lot of people mentioning auto as a blocker in their apps lately. good to hear it's coming through. we're also getting close to finalising the api

**Comment by lachlan-00** [comment]
I put a fallback in for version so that should help if you send a 400000 version you'll get a 500000 string back.

Ashot is working on the json but the XML I think is set now. Been testing on develop.ampache.dev without issue too.
