### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by IzzySoft** [4phun/amproid#7]
Are you planning to tag your releases and attach the APKs there, so they are also available outside the walled garden of Google Play?

**Comment by 4phun** [comment]
Hi,
Not sure what you mean by "tag your releases". Please elaborate.
Thank you

**Comment by IzzySoft** [comment]
Sure: please see https://github.com/4phun/amproid/releases – the link from there goes to detailed instructions; basically it's as simple as `git tag v1.2.3 && git push --tags` to create a tag for version 1.2.3 based on the current HEAD. After that, the linked page will offer you to "create a release", where you can add some release notes and also attach additional files, like the `*.apk` (using the second gray "attach file" box, so it ends up with the assets; the first one I've heard doesn't support APKs, and what's attached there ends up in the release notes).

That's how most Android App projects deal with it if they make their APKs available here. To give you an example of what it could look like: https://github.com/jgaa/VikingGTD/releases

**Comment by 4phun** [comment]
OK, I see what you mean. Sorry, it didn't click at first. Thank you for the explanation. Please give me a few days before I make a decision on this. Thank you.

**Comment by IzzySoft** [comment]
Sure, no prob. And no need to apologize: if you never used that before, how should you have known?

Please let me know when tags + APK are there. A comment of this issue (or even simply closing it) will notify me. Thanks!

**Comment by 4phun** [comment]
Hi, due to lack of time, I'm not going to do this. At least not for now. Sorry, I don't mean to disappoint, hope you understand.

**Comment by IzzySoft** [comment]
Well, it's your choice. But that way your app is stuck in the walled garden, you exclude all those not able (or willing) to go there (so this group won't be able to use your app) – and I can not, as planned, promote your app eg via [my repo](https://apt.izzysoft.de/fdroid). Not what I hoped for, but I'll of course accept your choice. All the best then for your project – and should you one day redecide, please let me know!

(PS: creating a tag and attaching a file usually takes less than a minute. While one usually adds some "changelog notes" there, too, those are not mandatory. So while I, as said, accept your decision, I can not understand the reasoning "lack of time" – unless you never build APKs and thus have nothing to attach; but how do they get to Play then?)
