### ISSUE TITLE
Clicking playlist, then press pause before playing causes "unspecified media Ayer error"

### ISSUE THREAD

**Issue by lachlan-00** [4phun/amproid#9]
Pressing play will start the list okay though

**Comment by 4phun** [comment]
Hi! Thank you for reporting this issue. Due to other things and projects, it will take some time, but eventually I will get to correct it.

**Comment by 4phun** [comment]
Hi!

I finally managed to release the new version 2.0.9 (requires Android 9 Pie or newer). At 2.0, Amproid went through a serious facelift, so this issue no longer applies.

Next release is planned for fall 2022, so there's still time to get your feature requests in :)
